
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://139.198.177.234:3306/im-core?serverTimezone=UTC&useSSL=false
    username: faka

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10
  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost
    username: guest
    password: guest
#    virtual-host:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0


# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8080

appConfig:
  zkAddr: 127.0.0.1:2181 # zk连接地址
  zkConnectTimeOut: 5000 #zk超时时间
  imRouteWay: 1 # 路由策略1轮训 2随机 3hash
  consistentHashWay: 1 # 如果选用一致性hash的话具体hash算法 1 TreeMap 2 自定义Map
  needWeb: true # 是否需要开启websocket
