lim:
  tcpPort: 9000 # tcp端口号
  enableWebSocket: true # 是否启用websocket
  webSocketPort: 19000 # webSocket端口号
  bossThreadSize: 1 # boss线程 默认=1
  businessThreadSize: 8 # 业务线程数 默认=cpu核心数
  enableCluster: false # 是否启用集群
  brokerId: 10000 # 集群brokerId
  heartBeatTime: 3000 # 心跳超时时间 单位毫秒
  loginModel: 2
  #  *                多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
  #  *                            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
  #  *                            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
  #  *                            4 允许所有端多设备登录 不踢任何设备
  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password:
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 127.0.0.1:6379
    cluster: #redis集群模式配置
      scanInterval: 1000
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      readMode: SLAVE
      retryAttempts: 3
      slaveConnectionPoolSize: 64
      masterConnectionPoolSize: 64
      retryInterval: 1500
    sentinel: #redis哨兵配置
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26379,127.0.0.1:26379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: guest
    password: guest